import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { MeshService } from '../src/service.js';
import { IntentStore } from '../src/store.js';
import { createServer } from '../src/server.js';
import { sha256, canonicalize } from '../src/canonical.js';

const route = () => ({ id: 'mock-usdc', rail: 'mock', network: 'sandbox', asset: 'USDC', online: true, feeBps: 10, fixedFeeMinor: 0, latencyMs: 80, supportsOfflineQueue: true, minAmountMinor: 1, maxAmountMinor: 1000000 });
const setup = store => new MeshService({ routes: [route()], store: store ?? new IntentStore(), signingSecret: 'test-secret' });
const input = (overrides = {}) => ({ idempotencyKey: `test-${Math.random()}`, agentId: 'agent_demo', beneficiary: 'ai-data-api', amountMinor: 250, asset: 'USDC', purpose: 'Dataset', ...overrides });

test('canonical payload hashes independently of property order', () => { assert.equal(sha256({ b: 2, a: 1 }), sha256({ a: 1, b: 2 })); assert.equal(canonicalize({ z: [1, 2], a: true }), '{"a":true,"z":[1,2]}'); });
test('agent creation assigns a separate policy and passport', () => { const s = setup(), a = s.createAgent({ name: 'Scout' }); assert.ok(a.passportId.startsWith('passport_')); assert.ok(s.store.find('policies', a.policyId)); });
test('invalid agent name is rejected', () => { assert.throws(() => setup().createAgent({ name: 'x' }), { code: 'INVALID_NAME' }); });
test('policy can be assigned to an agent', () => { const s = setup(), p = s.createPolicy({ maxAmountMinor: 10 }); assert.equal(s.assignPolicy('agent_demo', p.id).policyId, p.id); assert.throws(() => s.createIntent(input({ amountMinor: 11 })), { code: 'LIMIT_EXCEEDED' }); });
test('beneficiary denylist is enforced', () => { const s = setup(), p = s.createPolicy({ beneficiaryDenylist: ['ai-data-api'] }); s.assignPolicy('agent_demo', p.id); assert.throws(() => s.createIntent(input()), { code: 'BENEFICIARY_BLOCKED' }); });
test('idempotency conflict rejects changed payment', () => { const s = setup(), a = input(); s.createIntent(a); assert.throws(() => s.createIntent({ ...a, amountMinor: 500 }), { code: 'IDEMPOTENCY_CONFLICT' }); });
test('expired input is rejected', () => { assert.throws(() => setup().createIntent(input({ expiresAt: '2000-01-01T00:00:00Z' })), { code: 'INVALID_EXPIRY' }); });
test('offline intent reconciles exactly once when mock rail returns', async () => { const s = setup(); s.setMockOnline(false); const i = s.createIntent(input()); assert.equal(i.state, 'queued'); assert.equal((await s.reconcileQueued()).length, 0); s.setMockOnline(true); assert.equal((await s.reconcileQueued()).length, 1); assert.equal((await s.reconcileQueued()).length, 0); assert.equal(s.store.all('transactions').length, 1); });
test('concurrent execution shares one settlement', async () => { const s = setup(), i = s.createIntent(input()); const [a,b] = await Promise.all([s.execute(i.id),s.execute(i.id)]); assert.equal(a.id,b.id); assert.equal(s.store.all('transactions').length, 1); });
test('receipt binds executed intent hash', async () => { const s = setup(), i = s.createIntent(input()); const settled = await s.execute(i.id); assert.equal(settled.receipt.intentHash,i.intentHash); assert.match(settled.receipt.receiptHash,/^[a-f0-9]{64}$/); });
test('state survives store reinitialization', async () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(),'mesh-')); const file = path.join(dir,'state.json'); const s = setup(new IntentStore(file)); const i = s.createIntent(input()); await s.execute(i.id); const again = new IntentStore(file); assert.equal(again.get(i.id).state,'settled'); assert.equal(again.all('receipts').length,1); fs.rmSync(dir,{recursive:true,force:true}); });
test('HTTP UI and API complete the mock payment flow', async () => { const s=setup(), server=createServer({service:s,apiKey:'test-key'}); await new Promise(ok=>server.listen(0,'127.0.0.1',ok)); const base=`http://127.0.0.1:${server.address().port}`; const request=(p,method='GET',value)=>fetch(base+p,{method,headers:{'x-aifp4-api-key':'test-key','content-type':'application/json'},body:value?JSON.stringify(value):undefined}); try { const ui=await fetch(base+'/'); assert.equal(ui.status,200); assert.match(await ui.text(),/AIFP-4 Mesh/); const css=await fetch(base+'/styles.css'); assert.equal(css.status,200); const unauth=await fetch(base+'/v1/stats'); assert.equal(unauth.status,401); const made=await request('/v1/intents','POST',input()); assert.equal(made.status,201); const i=await made.json(); const execute=await request(`/v1/intents/${i.id}/execute`,'POST'); assert.equal((await execute.json()).state,'settled'); const receipt=await request(`/v1/receipts/${s.store.get(i.id).receipt.receiptId}`); assert.equal((await receipt.json()).intentHash,i.intentHash); } finally { await new Promise(ok=>server.close(ok)); } });

test('daily spending limit counts settled transactions', async () => { const s=setup(), p=s.createPolicy({dailyLimitMinor:300}); s.assignPolicy('agent_demo',p.id); const first=s.createIntent(input({amountMinor:250})); await s.execute(first.id); assert.throws(()=>s.createIntent(input({amountMinor:100})),{code:'DAILY_LIMIT_EXCEEDED'}); });
test('offline-disabled policy refuses queued intent', () => { const s=setup(), p=s.createPolicy({offlineAllowed:false}); s.assignPolicy('agent_demo',p.id); s.setMockOnline(false); assert.throws(()=>s.createIntent(input()),{code:'OFFLINE_BLOCKED'}); });
test('blocked asset has no executable route', () => { assert.throws(()=>setup().createIntent(input({asset:'BTC'})),{code:'ASSET_BLOCKED'}); });
test('execution of an expired intent does not settle', async () => { const s=setup(), i=s.createIntent(input()); i.expiresAt='2000-01-01T00:00:00Z'; const result=await s.execute(i.id); assert.equal(result.state,'expired'); assert.equal(s.store.all('transactions').length,0); });
test('repeated execution returns the same receipt', async () => { const s=setup(), i=s.createIntent(input()); const first=await s.execute(i.id), second=await s.execute(i.id); assert.equal(first.receipt.receiptId,second.receipt.receiptId); assert.equal(s.store.all('receipts').length,1); });
test('invalid policy arrays are rejected', () => { assert.throws(()=>setup().createPolicy({allowedRails:'mock'}),{code:'INVALID_POLICY'}); });
test('API network toggle and reconciliation settle queued payment', async () => { const s=setup(), server=createServer({service:s,apiKey:'key'}); await new Promise(ok=>server.listen(0,'127.0.0.1',ok)); const base=`http://127.0.0.1:${server.address().port}`, request=async(p,body)=>{const r=await fetch(base+p,{method:'POST',headers:{'x-aifp4-api-key':'key','content-type':'application/json'},body:JSON.stringify(body)});return r.json()}; try { await request('/v1/mesh/network',{online:false}); const i=await request('/v1/intents',input()); assert.equal(i.state,'queued'); await request('/v1/mesh/network',{online:true}); const result=await request('/v1/mesh/reconcile',{}); assert.equal(result.reconciled[0].state,'settled'); } finally { await new Promise(ok=>server.close(ok)); } });
test('unknown static paths and missing receipts are not exposed', async () => { const server=createServer({service:setup(),apiKey:'key'}); await new Promise(ok=>server.listen(0,'127.0.0.1',ok)); const base=`http://127.0.0.1:${server.address().port}`; try { assert.equal((await fetch(base+'/../package.json',{headers:{'x-aifp4-api-key':'key'}})).status,404); assert.equal((await fetch(base+'/v1/receipts/missing',{headers:{'x-aifp4-api-key':'key'}})).status,404); } finally { await new Promise(ok=>server.close(ok)); } });

test('SOL intent requires a valid Devnet recipient', () => { assert.throws(() => setup().createIntent(input({asset:'SOL'})),{code:'INVALID_BENEFICIARY'}); });
test('uncertain adapter result cannot be paid twice', async () => { const r={...route(),rail:'solana-devnet',id:'sol',asset:'SOL'}; const s=new MeshService({routes:[r],store:new IntentStore(),signingSecret:'test'}); s.registerAdapter('solana-devnet',{async execute(){throw Error('confirmation unknown')}}); const i=s.createIntent(input({asset:'SOL',beneficiary:'11111111111111111111111111111111',amountMinor:1000})); await assert.rejects(s.execute(i.id)); assert.equal(s.store.get(i.id).state,'executing'); await assert.rejects(s.execute(i.id),{code:'EXECUTION_UNCERTAIN'}); });
